version: 2.1
jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - run:
        name: Git Update
        command: ssh $SSH_USER@$SSH_HOST "cd educationleadshome.org && git pull --rebase"
      - run:
        name: Composer Update
        command: ssh $SSH_USER@$SSH_HOST "cd educationleadshome.org && composer install"
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
        filters:
          branches:
            only: master
